### ISSUE TITLE
Bot occasionally errors [Microsoft.Bot.Connector.ErrorResponseException: PreconditionFailed'], when multiple users send message to Bot server via directline at same time

### ISSUE THREAD

**Issue by rib-pet** [Microsoft/BotBuilder-V3#105]
## Version
What package version of the SDK are you using.

- package id="Microsoft.Bot.Builder" version="3.15.2.2" targetFramework="net46" 
- package id="Microsoft.Bot.Connector" version="3.15.2.2" targetFramework="net46" 

## Describe the bug
Give a clear and concise description of what the bug is.
When multiple users send messages to Bot server via directline at same time, the user who sent message later will come across an exception.

**Microsoft.Bot.Connector.ErrorResponseException: Operation returned an invalid status code 'PreconditionFailed'**

## To Reproduce

1.  multiple users sends message to bot server at same time. 

## Expected behavior
Give a clear and concise description of what you expected to happen.

- No any exception or errors

## Screenshots
![image](https://user-images.githubusercontent.com/37282473/51015006-5ae11b80-15a5-11e9-9a9c-b8e69230cacd.png)

Exception:
            Microsoft.Bot.Connector.ErrorResponseException: Operation returned an invalid status code 'PreconditionFailed'
   at Microsoft.Bot.Connector.BotState.&lt;SetUserDataWithHttpMessagesAsync&gt;d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Connector.BotStateExtensions.&lt;SetUserDataAsync&gt;d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.Dialogs.Internals.ConnectorStore.&lt;Microsoft-Bot-Builder-Dialogs-Internals-IBotDataStore&lt;Microsoft-Bot-Connector-BotData&gt;-SaveAsync&gt;d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.Dialogs.Internals.CachingBotDataStore.&lt;Save&gt;d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.Dialogs.Internals.CachingBotDataStore.&lt;Microsoft-Bot-Builder-Dialogs-Internals-IBotDataStore&lt;Microsoft-Bot-Connector-BotData&gt;-FlushAsync&gt;d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.Dialogs.Internals.BotDataBase`1.&lt;FlushAsync&gt;d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.Dialogs.Internals.DialogTaskManagerBotDataLoader.&lt;FlushAsync&gt;d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.Dialogs.Internals.PersistentDialogTask.&lt;Microsoft-Bot-Builder-Dialogs-Internals-IPostToBot-PostAsync&gt;d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

## Additional context

[bug]
[dotnet]

**Comment by rib-pet** [comment]
When I develop the directline, during one step : create conversation to the url (https://directline.botframework.com/v3/directline/conversations)

it requires that you must provide the following request body:
![image](https://user-images.githubusercontent.com/37282473/51015260-89132b00-15a6-11e9-99c9-8c0faa3f54c9.png)

I made a mistake, all conversations are based on the "From: user1". Actually, Everytime, you should create a unique "From" attribute when to create a conversation.

You can use Datetime to generate unique ID for "from" filed. it will fix your issue

**Comment by jwiley84** [comment]
Just to clarify, does this mean you've resolved your issue?

**Comment by rib-pet** [comment]
> Just to clarify, does this mean you've resolved your issue?

@jwiley84, Yes, Just ensure that you provide unique id to request bot service
