### ISSUE TITLE
[v3.15.0] [Messenger] 500 error when trying to send a message with Hero cards using session.send()

### ISSUE THREAD

**Issue by SamAlbuga** [Microsoft/BotBuilder-V3#111]
## Version
3.15.0

## Describe the bug
500 Error when trying to send a message with Hero Cards attachments using **session.send()**
```
POST to https://facebook.botframework.com/v3/conversations/***/activities/*** failed: [500] Internal Server Error
  at Request._callback (D:\home\site\wwwroot\node_modules\botbuilder\lib\bots\ChatConnector.js:647:46)
    at Request.self.callback (D:\home\site\wwwroot\node_modules\request\request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (D:\home\site\wwwroot\node_modules\request\request.js:1157:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (D:\home\site\wwwroot\node_modules\request\request.js:1079:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

## To Reproduce
```
 var msg = new builder.Message(session)
        .attachmentLayout(builder.AttachmentLayout.carousel)
        .attachments(cards)
        session.send(msg);
```

## Expected behavior
Send the message with the cards.

[bug]
[javascript]

**Comment by SamAlbuga** [comment]
I was sending an Object to builder.CardImage.create(_,_) instead of URL. After fixing that no more 500s
