### ISSUE TITLE
Problem with Bot Builder HeroCard

### ISSUE THREAD

**Issue by indobits** [Microsoft/BotBuilder-V3#114]
Hi, I have problems when I show HeroCards on Bot Framework. I used version 3.13.1.

**Comment by tdurnford** [comment]
Which SDK are you using - Node or C#? Also, can you please elaborate on the issue you are having and add the code where you are creating and sending the HeroCard so we can help you resolve your issue?

Additionally, I would recommend updating the BotFramework packages you are using to the most resent release - 3.16.0 for Node and 3.20.1 for C# were just released the other day.

**Comment by indobits** [comment]
I am using SDK 3 and Node. I've just upgraded bot builder to 3.16.0

```js
let button_attachment = new builder.HeroCard(session);
options = response.output.elements;
if(response.output.title && response.output.title != '') {
  button_attachment.title(response.output.title);
}
let buttons = [];
for(let i = 0; i < options.length; i++) {
  buttons[i] = builder.CardAction.openUrl(session, options[i].url, options[i].title);
}
console.log(buttons);
button_attachment.buttons(buttons);
arrMsg[arrMsg.length-1].attachments([button_attachment]);
```

**Comment by indobits** [comment]
My error is:

```
Error: POST to 'https://facebook.botframework.com/v3/conversations/XXX/activities/YYY' failed: [400] Bad Request
    at Request._callback (D:\home\site\wwwroot\node_modules\botbuilder\lib\bots\ChatConnector.js:675:46)
    at Request.self.callback (D:\home\site\wwwroot\node_modules\request\request.js:185:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (D:\home\site\wwwroot\node_modules\request\request.js:1161:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (D:\home\site\wwwroot\node_modules\request\request.js:1083:12)
    at IncomingMessage.g (events.js:291:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

**Comment by tdurnford** [comment]
It looks like there are two potential issues with your code. 

First, in the last line of the code you added, use the `addAttachment` method instead of the `attachments` function.

```
arrMsg[arrMsg.length-1].addAttachment([button_attachment]);
```

Secondly, it appears that you are trying to send an array of messages to the user. Sending multiple messages is fine, but you need to send them all individually. The code to send the `arrMsg` array should have the same functionality as the code below.

```
messages.forEach(message => session.send(message))
```

Please let me know if this solves your issue - if not, we can dig deeper. Hope this helps!

**Comment by CoHealer** [comment]
@indobits . does this solve your issue?

**Comment by CoHealer** [comment]
No response from user, closing
