### ISSUE TITLE
Bot is failing to communicate on Facebook Channel ( Bad Request )

### ISSUE THREAD

**Issue by Alexander-0x80** [microsoft/BotBuilder-V3#132]
## Version
```
"botbuilder": "^3.13.1",
"botbuilder-azure": "^3.0.4"
```

## Describe the bug
Bot was working fine for a lot of time ( on Facebook Channel ), no code changes where made.
From 15/04/2019 Bot stopped responding to Facebook messages with the following error:

```
Error: POST to 'https://facebook.botframework.com/v3/conversations/xxxxxxxxxxxxxxxxx-xxxxxxxxxxxxxxxxx/activities/vM8xdHOumCjl_b_wdJMclUXt8gbAMoHzCIklsYqfTeWLMmK49afoLlymD-y_42dRmhTgMkfL399qBQwD-iVGjQ' failed: [400] Bad Request
    at Request._callback (/home/bots/node_modules/botbuilder/lib/bots/ChatConnector.js:675:46)
    at Request.self.callback (/home/bots/node_modules/request/request.js:185:22)
    at Request.emit (events.js:197:13)
    at Request.EventEmitter.emit (domain.js:446:20)
    at Request.<anonymous> (/home/bots/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:197:13)
    at Request.EventEmitter.emit (domain.js:446:20)
    at IncomingMessage.<anonymous> (/home/bots/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:285:13)
    at IncomingMessage.emit (events.js:202:15)
    at IncomingMessage.EventEmitter.emit (domain.js:446:20)
    at endReadableNT (_stream_readable.js:1129:12)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)
```

Web Chat on Azure Portal works as expected.
Looking at 'Connected Channels' View on Azure Portal shows no issues at all !

<img width="572" alt="image" src="https://user-images.githubusercontent.com/1289062/56275406-50d13a80-6109-11e9-9cb9-558d17788188.png">

Incoming messages are received by the bot. Issue arises when bot tries to reply to a message. 
Have no ideas how to debug this further.

[bug]
[javascript]

**Comment by EricDahlvang** [comment]
Hi @Alexander-0x80 

Do you have Application Insights configured for the bot? You should be able to find more information about this error there.

Have you tried refreshing your facebook page token?  

It looks like this is on the Facebook end: 

> (#2022) Your account has been disabled. If you have any questions or concerns, you can visit our FAQ page.

**Comment by Alexander-0x80** [comment]
Hi @EricDahlvang 

Yes, i have Application Insights configured, but i don't seem to find any error related information there.
Also i have tried multiple times to refresh my token. 

This Error message you have attached, how did you find it ? 
I am able to login/logout from Facebook without any issue, so this is really confusing.

**Comment by EricDahlvang** [comment]
This error should be propagated back to your bot if you are logging exceptions.  It shows in our logs.

**Comment by Alexander-0x80** [comment]
The exceptions are being logged in app insights, this is how it looks like:

<img width="1201" alt="image" src="https://user-images.githubusercontent.com/1289062/56588705-8c2da680-65ec-11e9-945e-59745de56215.png">

We do not see any error description there. Only status codes as i mentioned above.
I would really appreciate if you could guide me how to find it.

Also you mention that "in our logs" you see the error message. Are we talking about a same 
bot ? because we are running multiple bots on this account.

**Comment by EricDahlvang** [comment]
No, that looks like a bug.  The Health column should be showing exceptions, and your application insights should show the Facebook API error as well.  I will investigate further, and get back to you.

**Comment by EricDahlvang** [comment]
Hi @Alexander-0x80 

I apologize for the late response.  An engineer is investigating why this error is not showing in the bot's health column.  I'll let you know when I get more information.

**Comment by EricDahlvang** [comment]
@Alexander-0x80 please share the Bot Handle for this bot.  If you prefer, you can email it to me on the address on my profile.

**Comment by EricDahlvang** [comment]
@Alexander-0x80 

We are logging invalid token errors:

![image](https://user-images.githubusercontent.com/11055362/59867980-7e727400-9344-11e9-9693-b6a680fa8d87.png)

If you see a similar problem, where we are not logging Facebook Messenger connector errors in the health column, please open a new issue.
