### ISSUE TITLE
Autofac.Core.DependencyResolutionException throwing when to call Conversation.SendAsync method

### ISSUE THREAD

**Issue by rib-pet** [microsoft/BotBuilder-V3#149]
## Version
What package version of the SDK are you using.
3.20.1.42
## Describe the bug
Give a clear and concise description of what the bug is.
Just startup Bot source code. it gives me the exception "Autofac.Core.DependencyResolutionException"
## To Reproduce
Debug bot via Emulator

## Expected behavior
Give a clear and concise description of what you expected to happen.
No exceptions

## Screenshots
![image](https://user-images.githubusercontent.com/37282473/59345438-ac532980-8d42-11e9-8bf7-b373f2794b3b.png)

![image](https://user-images.githubusercontent.com/37282473/59345501-d4428d00-8d42-11e9-86b1-08e305d3b479.png)

## Additional context

iisexpress.exe Error: 0 : Autofac.Core.DependencyResolutionException: An exception was thrown while activating λ:Microsoft.Bot.Builder.Dialogs.Internals.IPostToBot -> Microsoft.Bot.Builder.Dialogs.Internals.QueueDrainingDialogTask -> λ:Microsoft.Bot.Builder.Dialogs.Internals.IBotToUser -> Microsoft.Bot.Builder.Dialogs.Internals.AlwaysSendDirect_BotToUser -> λ:Microsoft.Bot.Connector.IConnectorClient -> λ:Microsoft.Bot.Builder.Dialogs.Internals.ConnectorClientFactory. ---> System.AggregateException: One or more errors occurred. ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 18.188.14.65:443
   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Rest.RetryDelegatingHandler.<>c__DisplayClass11_0.<<SendAsync>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Rest.RetryDelegatingHandler.<SendAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Connector.OAuthApi.<SendEmulateOAuthCardsAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.Dialogs.Internals.ConnectorClientFactory.<>c__DisplayClass9_1.<<-ctor>b__0>d.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.Internals.ConnectorClientFactory..ctor(IAddress address, MicrosoftAppCredentials credentials)
   at Microsoft.Bot.Builder.Dialogs.Internals.DialogModule.<>c.<Load>b__5_5(IComponentContext c)
   at Autofac.Builder.RegistrationBuilder.<>c__DisplayClass0_0`1.<ForDelegate>b__0(IComponentContext c, IEnumerable`1 p)
   at Autofac.Core.Activators.Delegate.DelegateActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters, Object& decoratorTarget)
   --- End of inner exception stack trace ---
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters, Object& decoratorTarget)
   at Autofac.Core.Lifetime.LifetimeScope.GetOrCreateAndShare(Guid id, Func`1 creator)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.ResolveOperation.Execute(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve[TService](IComponentContext context, IEnumerable`1 parameters)
   at Microsoft.Bot.Builder.Dialogs.Conversation.<SendAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.Dialogs.Conversation.<SendAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at RIB.Visual.Mtwo.Mctwo.BotService.Controllers.MessagesController.<Post>d__1.MoveNext() in D:\ITWO city\trunk\RIB.Visual.MCTWO.BotService\Controllers\MessagesController.cs:line 127

[bug]
[dotnet]

**Comment by EricDahlvang** [comment]
Hi @rib-pet 

Please share your packages.config, as well as autofac registration code (Global.asax.cs).  Or, can you share the entire project?  

I am not able to reproduce this.

**Comment by EricDahlvang** [comment]
Closing due to no response.
