### ISSUE TITLE
[Question, bug] Bot framework fails to save state to Doc DB in Teams 1:1 conversation (and errors dialogue)

### ISSUE THREAD

**Issue by Eli2590** [microsoft/BotBuilder-V3#207]
## Version
3.30.0.1

## Describe the bug
When user initiates a new 1:1 conversation in MS Teams, bot errors out. Does not happen consistently - some users work, some don't. I saw this error when we were using 3.15 version and according to the fix I updated it to 3.30. But the error appeared again.

## To Reproduce
Create bot with Teams channel enabled.
Onboard bot to DocDB.
Initiate conversation with bot account.

## Expected behavior
Bot to respond correctly and save dialogue state.

[bug]
[dotnet]

**Comment by mdrichardson** [comment]
@Eli2590 Can you provide Conversation IDs for when the error appears or appId and timestamps?

I think I mentioned before we're only doing security bug-fixes in V3, but I can look to make sure there isn't something going on on the service side.

**Comment by Eli2590** [comment]
@mdrichardson Here are the Conversation IDs
![image](https://user-images.githubusercontent.com/62258224/81653539-93189880-943d-11ea-9ef6-609bf9e7f14a.png)

stack trace:
Caught unhandled exception. CancellationRequest = False.: at PostAsync in C:\source\Src\Tools\KusBot\Common\CustomPostToUser.cs: line 43
***
Message: {"Errors":["The input name is invalid. Ensure to provide a unique non-empty string less than '255' characters."]}
ActivityId: bcbb6c11-0ccd-4ebc-ac6c-f20d3c4fdab6, Request URI: /apps/2c77ff9f-6270-4ef5-9744-6cc65ce3cbc6/services/d5d35d6b-3e81-43cf-8162-bebae5951a60/partitions/0cd620c7-8883-4ce3-85ab-953198b18273/replicas/132327472190364493p/, RequestStats: 
RequestStartTime: 2020-05-11T12:45:34.1858975Z, RequestEndTime: 2020-05-11T12:45:34.1858975Z,  Number of regions attempted:1
ResponseTime: 2020-05-11T12:45:34.1858975Z, StoreResult: StorePhysicalAddress: rntbd://byaprdapp05-docdb-2.documents.azure.com:14059/apps/2c77ff9f-6270-4ef5-9744-6cc65ce3cbc6/services/d5d35d6b-3e81-43cf-8162-bebae5951a60/partitions/0cd620c7-8883-4ce3-85ab-953198b18273/replicas/132327472190364493p/, LSN: 1661295, GlobalCommittedLsn: 1661295, PartitionKeyRangeId: 0, IsValid: True, StatusCode: 400, SubStatusCode: 0, RequestCharge: 2.38, ItemLSN: -1, SessionToken: 1661295, UsingLocalLSN: False, TransportException: null, ResourceType: Document, OperationType: Upsert
, SDK: Microsoft.Azure.Documents.Common/2.10.0
System.Web.HttpException (0x80004005): Message: {"Errors":["The input name is invalid. Ensure to provide a unique non-empty string less than '255' characters."]}
ActivityId: bcbb6c11-0ccd-4ebc-ac6c-f20d3c4fdab6, Request URI: /apps/2c77ff9f-6270-4ef5-9744-6cc65ce3cbc6/services/d5d35d6b-3e81-43cf-8162-bebae5951a60/partitions/0cd620c7-8883-4ce3-85ab-953198b18273/replicas/132327472190364493p/, RequestStats: 
RequestStartTime: 2020-05-11T12:45:34.1858975Z, RequestEndTime: 2020-05-11T12:45:34.1858975Z,  Number of regions attempted:1
ResponseTime: 2020-05-11T12:45:34.1858975Z, StoreResult: StorePhysicalAddress: rntbd://byaprdapp05-docdb-2.documents.azure.com:14059/apps/2c77ff9f-6270-4ef5-9744-6cc65ce3cbc6/services/d5d35d6b-3e81-43cf-8162-bebae5951a60/partitions/0cd620c7-8883-4ce3-85ab-953198b18273/replicas/132327472190364493p/, LSN: 1661295, GlobalCommittedLsn: 1661295, PartitionKeyRangeId: 0, IsValid: True, StatusCode: 400, SubStatusCode: 0, RequestCharge: 2.38, ItemLSN: -1, SessionToken: 1661295, UsingLocalLSN: False, TransportException: null, ResourceType: Document, OperationType: Upsert
, SDK: Microsoft.Azure.Documents.Common/2.10.0 ---> Microsoft.Azure.Documents.DocumentClientException: Message: {"Errors":["The input name is invalid. Ensure to provide a unique non-empty string less than '255' characters."]}
ActivityId: bcbb6c11-0ccd-4ebc-ac6c-f20d3c4fdab6, Request URI: /apps/2c77ff9f-6270-4ef5-9744-6cc65ce3cbc6/services/d5d35d6b-3e81-43cf-8162-bebae5951a60/partitions/0cd620c7-8883-4ce3-85ab-953198b18273/replicas/132327472190364493p/, RequestStats: 
RequestStartTime: 2020-05-11T12:45:34.1858975Z, RequestEndTime: 2020-05-11T12:45:34.1858975Z,  Number of regions attempted:1
ResponseTime: 2020-05-11T12:45:34.1858975Z, StoreResult: StorePhysicalAddress: rntbd://byaprdapp05-docdb-2.documents.azure.com:14059/apps/2c77ff9f-6270-4ef5-9744-6cc65ce3cbc6/services/d5d35d6b-3e81-43cf-8162-bebae5951a60/partitions/0cd620c7-8883-4ce3-85ab-953198b18273/replicas/132327472190364493p/, LSN: 1661295, GlobalCommittedLsn: 1661295, PartitionKeyRangeId: 0, IsValid: True, StatusCode: 400, SubStatusCode: 0, RequestCharge: 2.38, ItemLSN: -1, SessionToken: 1661295, UsingLocalLSN: False, TransportException: null, ResourceType: Document, OperationType: Upsert
, SDK: Microsoft.Azure.Documents.Common/2.10.0
   at Microsoft.Azure.Documents.Client.ClientExtensions.<ParseResponseAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Documents.GatewayStoreModel.<>c__DisplayClass10.<<InvokeAsync>b__f>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Documents.BackoffRetryUtility`1.<>c__DisplayClass2.<<ExecuteAsync>b__0>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Documents.BackoffRetryUtility`1.<ExecuteRetry>d__1b.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Azure.Documents.BackoffRetryUtility`1.<ExecuteRetry>d__1b.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Documents.BackoffRetryUtility`1.<ExecuteAsync>d__a.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Documents.GatewayStoreModel.<InvokeAsync>d__1f.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Documents.GatewayStoreModel.<ProcessMessageAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Documents.Client.DocumentClient.<UpsertAsync>d__31c.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Documents.Client.DocumentClient.<UpsertDocumentPrivateAsync>d__264.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Documents.BackoffRetryUtility`1.<>c__DisplayClass2.<<ExecuteAsync>b__0>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Documents.BackoffRetryUtility`1.<ExecuteRetry>d__1b.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Azure.Documents.BackoffRetryUtility`1.<ExecuteRetry>d__1b.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Documents.BackoffRetryUtility`1.<ExecuteAsync>d__a.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Documents.Client.DocumentClient.<UpsertDocumentAsync>d__25d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.Azure.DocumentDbBotDataStore.<Microsoft-Bot-Builder-Dialogs-Internals-IBotDataStore<Microsoft-Bot-Connector-BotData>-SaveAsync>d__7.MoveNext()
   at Microsoft.Bot.Builder.Azure.DocumentDbBotDataStore.<Microsoft-Bot-Builder-Dialogs-Internals-IBotDataStore<Microsoft-Bot-Connector-BotData>-SaveAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.Dialogs.Internals.CachingBotDataStore.<Save>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.Dialogs.Internals.CachingBotDataStore.<Microsoft-Bot-Builder-Dialogs-Internals-IBotDataStore<Microsoft-Bot-Connector-BotData>-FlushAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.Dialogs.Internals.BotDataBase`1.<FlushAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.Dialogs.Internals.DialogTaskManagerBotDataLoader.<FlushAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.Dialogs.Internals.PersistentDialogTask.<Microsoft-Bot-Builder-Dialogs-Internals-IPostToBot-PostAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.Dialogs.Internals.ExceptionTranslationDialogTask.<Microsoft-Bot-Builder-Dialogs-Internals-IPostToBot-PostAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.Dialogs.Internals.SerializeByConversation.<Microsoft-Bot-Builder-Dialogs-Internals-IPostToBot-PostAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at KusBot.Common.CustomPostToUser.<Microsoft-Bot-Builder-Dialogs-Internals-IPostToBot-PostAsync>d__3.MoveNext() in C:\source\Src\Tools\KusBot\Common\CustomPostToUser.cs:line 38

**Comment by mdrichardson** [comment]
@Eli2590 Thank you. I'll start looking on the backend. Can you please copy/paste your `packages.config` as well as your `CustomPostToUser.cs`? 

I see the error: `"Errors":["The input name is invalid. Ensure to provide a unique non-empty string less than '255' characters."]}`. Are you using a custom storage adapter? If so, please include that as well.

**Comment by cleemullins** [comment]
Note: The v3.30 SDK doesn't really support DocDB or Teams.

**Comment by EricDahlvang** [comment]
@cleemullins technically v3.30 does support DocumentDb/CosmosDb and Teams

I believe this was added specifically due to the older docdb key length restrictions, and Teams long conversation.ids:
https://github.com/microsoft/BotBuilder-V3/blob/master/Azure/CSharp/Library/Microsoft.Bot.Builder.Azure/DocumentDbBotDataStore.cs#L306

```cs
        private static string TruncateEntityKey(string entityKey)
        {
            if (entityKey.Length > MAX_KEY_LENGTH)
            {
                var hash = entityKey.GetHashCode().ToString("x");
                entityKey = entityKey.Substring(0, MAX_KEY_LENGTH - hash.Length) + hash;
            }

            return entityKey;
        }
```

And this package has been around for a few years: 
https://www.nuget.org/packages/Microsoft.Bot.Connector.Teams/0.10.0
![image](https://user-images.githubusercontent.com/11055362/81865529-e1539780-9522-11ea-9b7a-a13c02a20073.png)

Nonetheless, these are all deprecated and unsupported libraries.

**Comment by Eli2590** [comment]
@EricDahlvang Thanks a lot. I'll try to update the packages

**Comment by mdrichardson** [comment]
@Eli2590 Any luck?

**Comment by Eli2590** [comment]
@mdrichardson Did not encounter with the issue again. Thanks
