### ISSUE TITLE
[Skype] Botframework publishing review ping test failed

### ISSUE THREAD

**Issue by boychyk** [Microsoft/BotBuilder-V3#6]
## Version
* SDK: .Net Core 2.1
* Deployment Environment: Azure Bot Service
* Microsoft.Bot.Connector Version: 3.15.3

## Issue description
I'am trying to publish my bot. During test ping request I get InternalServerError. The connector client makes POST request on https://dev.botframework.com/v3/conversations/test/activities but instead of json it gets some html.
So app throws Newtonsoft.Json.JsonReaderException:

> Unable to deserialize the response. Unexpected character encountered while parsing value: <. Path '', line 0, position 0.

Bot works properly in unpublished Skype and Web Chat channels.

Here's call stack:

```
Microsoft.Rest.SerializationException:
   at Microsoft.Bot.Connector.Conversations+<SendToConversationWithHttpMessagesAsync>d__7.MoveNext (Microsoft.Bot.Connector, Version=3.15.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.Bot.Connector.ConversationsExtensions+<SendToConversationAsync>d__5.MoveNext (Microsoft.Bot.Connector, Version=3.15.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at SoftServe.ThinkIterateDeliver.BotServiceApp.BL.Implementation.ActivityDispatcher+<ProcessActivity>d__4.MoveNext (SoftServe.ThinkIterateDeliver.BotServiceApp.BL, Version=1.0.0.0, Culture=neutral, PublicKeyToken=nullSoftServe.ThinkIterateDeliver.BotServiceApp.BL, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null: C:\Build\Agent_06\11\s\SoftServe.ThinkIterateDeliver.BotServiceApp.BL\Implementation\ActivityDispatcher.csSoftServe.ThinkIterateDeliver.BotServiceApp.BL, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null: 54)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at SoftServe.ThinkIterateDeliver.BotServiceApp.Web.Controllers.Api.InteractionController+<ProcessMessage>d__2.MoveNext (SoftServe.ThinkIterateDeliver.BotServiceApp.Web, Version=1.0.0.1, Culture=neutral, PublicKeyToken=nullSoftServe.ThinkIterateDeliver.BotServiceApp.Web, Version=1.0.0.1, Culture=neutral, PublicKeyToken=null: C:\Build\Agent_06\11\s\SoftServe.ThinkIterateDeliver.BotServiceApp.Web\Controllers\Api\InteractionController.csSoftServe.ThinkIterateDeliver.BotServiceApp.Web, Version=1.0.0.1, Culture=neutral, PublicKeyToken=null: 35)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter1.GetResult (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor+TaskOfIActionResultExecutor+<Execute>d__0.MoveNext (Microsoft.AspNetCore.Mvc.Core, Version=2.1.3.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Threading.Tasks.ValueTask1.get_Result (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.ValueTaskAwaiter1.GetResult (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeActionMethodAsync>d__12.MoveNext (Microsoft.AspNetCore.Mvc.Core, Version=2.1.3.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeNextActionFilterAsync>d__10.MoveNext (Microsoft.AspNetCore.Mvc.Core, Version=2.1.3.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow (Microsoft.AspNetCore.Mvc.Core, Version=2.1.3.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next (Microsoft.AspNetCore.Mvc.Core, Version=2.1.3.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeInnerFilterAsync>d__13.MoveNext (Microsoft.AspNetCore.Mvc.Core, Version=2.1.3.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeNextExceptionFilterAsync>d__24.MoveNext (Microsoft.AspNetCore.Mvc.Core, Version=2.1.3.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
Inner exception Newtonsoft.Json.JsonReaderException handled at Microsoft.Bot.Connector.Conversations+<SendToConversationWithHttpMessagesAsync>d__7.MoveNext:
   at Newtonsoft.Json.JsonTextReader.ParseValue (Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed)
   at Newtonsoft.Json.JsonTextReader.Read (Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed)
   at Newtonsoft.Json.JsonReader.ReadForType (Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize (Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal (Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed)
   at Microsoft.Rest.Serialization.SafeJsonConvert.DeserializeObject (Microsoft.Rest.ClientRuntime, Version=2.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at Microsoft.Bot.Connector.Conversations+<SendToConversationWithHttpMessagesAsync>d__7.MoveNext (Microsoft.Bot.Connector, Version=3.15.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
```

**Comment by jwiley84** [comment]
Investigating!

**Comment by boychyk** [comment]
Hello @jwiley84! This is the method that makes a request:
`client.Conversations.SendToConversationAsync(processedConversation.ReplyActivity)`

Here's the `client` is ClientConnector and `ReplyActivity` is the result from activity.CreateReply().

**Comment by jwiley84** [comment]
Alrighty. Can I get your BotID, please?

**Comment by CoHealer** [comment]
@boychyk , can you please provide the BotID requested a while ago? 

@Prybe, can you please open a separate issue in the BotBuilder repo? It will better assist in our tracking and reporting, thx.

**Comment by jwiley84** [comment]
@CoHealer, @Prybe opened the issue [here](https://github.com/Microsoft/botbuilder-dotnet/issues/1074) and I have @boychyk 's botid in my email.

**Comment by CoHealer** [comment]
Ack, thanks

**Comment by CoHealer** [comment]
Closing due to inactivity. @boychyk , please reopen if the issue persists.

**Comment by Prybe** [comment]
Hi, the issue still persists!

Here is the message when i click the "submit for review"

`{
	"type": "event",
	"id": "DolLCbM7LCc",
	"timestamp": "0001-01-01T00:00:00+00:00",
	"localTimestamp": null,
	"localTimezone": null,
	"serviceUrl": "https://dev.botframework.com/",
	"channelId": "test",
	"from": {
		"id": "portal",
		"name": null,
		"aadObjectId": null,
		"role": null
	},
	"conversation": {
		"isGroup": null,
		"conversationType": null,
		"id": "test",
		"name": null,
		"aadObjectId": null,
		"role": null
	},
	"recipient": {
		"id": "obstaclerangers-bot-prod",
		"name": null,
		"aadObjectId": null,
		"role": null
	},
	"textFormat": null,
	"attachmentLayout": null,
	"membersAdded": null,
	"membersRemoved": null,
	"reactionsAdded": null,
	"reactionsRemoved": null,
	"topicName": null,
	"historyDisclosed": null,
	"locale": null,
	"text": null,
	"speak": null,
	"inputHint": null,
	"summary": null,
	"suggestedActions": null,
	"attachments": null,
	"entities": null,
	"channelData": null,
	"action": null,
	"replyToId": null,
	"label": null,
	"valueType": null,
	"value": null,
	"name": "test",
	"relatesTo": null,
	"code": null,
	"expiration": null,
	"importance": null,
	"deliveryMode": null,
	"listenFor": null,
	"textHighlights": null,
	"semanticAction": null
}`

And when I reply i got the following exception:

`Exception caught : Microsoft.Rest.SerializationException: Unable to deserialize the response. ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Microsoft.Rest.Serialization.SafeJsonConvert.DeserializeObject[T](String json, JsonSerializerSettings settings)
   at Microsoft.Bot.Connector.Conversations.ReplyToActivityWithHttpMessagesAsync(String conversationId, String activityId, Activity activity, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.Bot.Connector.Conversations.ReplyToActivityWithHttpMessagesAsync(String conversationId, String activityId, Activity activity, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Bot.Connector.ConversationsExtensions.ReplyToActivityAsync(IConversations operations, String conversationId, String activityId, Activity activity, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.BotFrameworkAdapter.SendActivitiesAsync(ITurnContext turnContext, Activity[] activities, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.TurnContext.<>c__DisplayClass22_0.<<SendActivitiesAsync>g__SendActivitiesThroughAdapter|1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Bot.Builder.TurnContext.SendActivityAsync(IActivity activity, CancellationToken cancellationToken)
   at RangerChatbot.RootDialog.OnTurnAsync(ITurnContext context, CancellationToken cancellationToken) in D:\a\1\s\RangerChatbot\RangerChatbot\Dialogs\RootDialog.cs:line 154
   at Microsoft.Bot.Builder.MiddlewareSet.ReceiveActivityWithStatusAsync(ITurnContext turnContext, BotCallbackHandler callback, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.BotAdapter.RunPipelineAsync(ITurnContext turnContext, BotCallbackHandler callback, CancellationToken cancellationToken)`

**Comment by CoHealer** [comment]
Using [#1074](https://github.com/Microsoft/botbuilder-dotnet/issues/1074) to track
