### ISSUE TITLE
AdalAuthenticator does not accept empty MicrosoftAppId and MicrosoftAppPassword

### ISSUE THREAD

**Issue by EricDahlvang** [Microsoft/BotBuilder-V3#68]
## Version
Clean pull of the repository.

## Describe the bug
ArgumentNullException when messaging a bot without MicrosoftAppId and MicrosoftAppPassword

## To Reproduce
1. download the source
2. set EchoBot as the startup project
3. remove the MicrosoftAppId and MicrosoftAppPassword from web.config
4. run the bot
5. connect to the local bot from the emulator without appid and password
6. send the bot a message and observe exception

> System.ArgumentNullException: 'Value cannot be null.
> Parameter name: clientId'
> 
> 

Stack Trace:
 

>   at Microsoft.IdentityModel.Clients.ActiveDirectory.ClientCredential..ctor(String clientId, String clientSecret)
>    at Microsoft.Bot.Connector.MicrosoftAppCredentials..ctor(String appId, String password) in C:\work\v3\clean11.16.2018\BotBuilder-V3\CSharp\Library\Microsoft.Bot.Connector.Shared\MicrosoftAppCredentials.cs:line 65
>    at lambda_method(Closure , Object[] )
>    at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()

## Expected behavior
Communicating with a bot from the emulator without an appid and password in bot or emulator should work

## Screenshots
![image](https://user-images.githubusercontent.com/11055362/48642964-3dbc1200-e993-11e8-9d48-84209c87c86e.png)

## Additional context
Introduced with https://github.com/Microsoft/BotBuilder-V3/pull/53

[bug]
[dotnet]

**Comment by carlosscastro** [comment]
This is being fixed in a PR today along with other changes. Good catch @EricDahlvang !!!

**Comment by CoHealer** [comment]
@EricDahlvang, please close upon verification, thx.

**Comment by EricDahlvang** [comment]
Fixed!
